"""Service for generating structured export reports in Markdown and JSON."""
from typing import Dict, Any

class ExportService:
    """Generates human-readable Markdown summary and structured contract export."""

    @classmethod
    def generate_markdown_report(cls, contract_ir: Dict[str, Any]) -> str:
        """Create a complete decision map summary report in Markdown."""
        meta = contract_ir.get("metadata", {})
        title = meta.get("title", meta.get("filename", "Contract Document"))
        parties = meta.get("parties", [])
        eff_date = meta.get("effective_date", "Not specified")
        exp_date = meta.get("expiration_date", "Not specified")
        tenure = meta.get("tenure_months", "N/A")
        
        md_lines = [
            f"# ContractLens Executive Decision Map",
            f"**Document**: {title}  ",
            f"**SHA-256**: `{meta.get('sha256', '')}`  ",
            f"**Traceability Rate**: {meta.get('traceability_rate', 100)}% Grounded  ",
            f"\n---",
            f"\n## 1. Agreement Overview & Parties",
            f"- **Effective Date**: {eff_date}",
            f"- **Expiration Date**: {exp_date}",
            f"- **Tenure**: {tenure} months\n"
        ]

        if parties:
            md_lines.append("### Parties Involved")
            for p in parties:
                role = p.get("role", "Party")
                name = p.get("name", "Unknown")
                ptype = p.get("type", "")
                md_lines.append(f"- **{role}**: {name} ({ptype})" if ptype else f"- **{role}**: {name}")

        # Financial Terms
        fin_terms = contract_ir.get("financial_terms", [])
        if fin_terms:
            md_lines.append("\n## 2. Financial Breakdown & Liability Schedule")
            md_lines.append("| Type | Label | Amount | Frequency | Trigger | Source Reference |")
            md_lines.append("|---|---|---|---|---|---|")
            for ft in fin_terms:
                md_lines.append(
                    f"| {ft.get('type', 'commitment')} | {ft.get('label', '')} | {ft.get('currency', 'INR')} {ft.get('amount', 0):,} | {ft.get('frequency', 'one_time')} | {ft.get('trigger', '')} | `{ft.get('source_id', '')}` |"
                )

        # Critical Deadlines
        deadlines = contract_ir.get("deadlines", [])
        if deadlines:
            md_lines.append("\n## 3. Timeline & Critical Milestones")
            for dl in deadlines:
                tier = dl.get("attention_tier", "medium").upper()
                badge = "🔴" if tier == "HIGH" else ("🟠" if tier == "MEDIUM" else "🟡")
                md_lines.append(
                    f"- {badge} **{dl.get('date', 'Due Date')} ({dl.get('relative_label', '')})**: {dl.get('event', '')} — *Action*: {dl.get('action', '')}. *Consequence*: {dl.get('consequence', '')}"
                )

        # Attention Findings
        findings = contract_ir.get("findings", [])
        if findings:
            md_lines.append("\n## 4. Attention Findings & Hidden Risks")
            for f in findings:
                tier = f.get("severity_tier", "medium").upper()
                badge = "🔴" if tier == "HIGH" else ("🟠" if tier == "MEDIUM" else "🟡")
                ambig = " ⚠️ [Ambiguity Detected]" if f.get("ambiguity_detected") else ""
                md_lines.append(f"\n### {badge} [{tier}] {f.get('title', '')}{ambig}")
                md_lines.append(f"**Category**: {f.get('category', '')} | **Source**: `{f.get('source_id', '')}`")
                md_lines.append(f"\n{f.get('explanation', '')}")
                md_lines.append(f"\n**Why it matters**: {f.get('matters', '')}")
                if f.get("bullets"):
                    md_lines.append("\n*Actionable items*:")
                    for b in f.get("bullets", []):
                        md_lines.append(f"- {b}")
                if f.get("evidence"):
                    md_lines.append(f"\n> **Verbatim Contract Evidence**: \"{f.get('evidence')}\"")

        # Obligations
        obligations = contract_ir.get("obligations", [])
        if obligations:
            md_lines.append("\n## 5. Obligations & Rights")
            for ob in obligations:
                md_lines.append(f"- **{ob.get('actor', 'Party')}**: {ob.get('action', '')}" + (f" (*Condition*: {ob.get('condition')})" if ob.get("condition") else ""))

        md_lines.append("\n---\n*Generated by ContractLens Visual Contract Intelligence*")
        return "\n".join(md_lines)
